version: '3.7'

services:
  avensia_github_scraper:
    #env_file:
    #  - dev.env
    container_name: avensia_github_scraper
    #image: node:16-alpine
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./api/src:/home/node/app/src
      - ./api/nodemon.json:/home/node/app/nodemon.json
    #args:
    #NODE_WORKDIR: ${NODE_WORKDIR} # from .env file
    #working_dir: $NODE_WORKDIR
    #environment:
    #  - NODE_ENV=$NODE_DOCKER_ENV
    #volumes:
    # - ./app:$NODE_WORKDIR
    expose:
      - 4000
    ports:
      - 4000:4000
    command: npm run dev
